### ISSUE TITLE
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1   0%|  

### ISSUE THREAD

**Issue by gadiluna** [zphang/minimal-llama#2]
When running the finetuning with peft with the command: 

`python finetune_peft.py     --model_path ../../LLaMAHF/llama-7b/     --dataset_path ../../tokenizedinstruct/     --peft_mode lora     --lora_rank 8     --per_device_train_batch_size 2     --gradient_accumulation_steps 1     --max_steps 30000     --learning_rate 2e-4     --fp16     --logging_steps 100     --output_dir  ../../LLaMAPEFT/llamapeft-7B/`

The finetuning does not start. The error is:
```

  0%|                                                                                                        | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "finetune_peft.py", line 142, in <module>
    main()
  File "finetune_peft.py", line 137, in main
    trainer.train()
  File "/opt/conda/envs/llama/lib/python3.8/site-packages/transformers/trainer.py", line 1628, in train
    return inner_training_loop(
  File "/opt/conda/envs/llama/lib/python3.8/site-packages/transformers/trainer.py", line 1895, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/envs/llama/lib/python3.8/site-packages/transformers/trainer.py", line 2637, in training_step
    loss = self.compute_loss(model, inputs)
  File "finetune_peft.py", line 80, in compute_loss
    return model(
  File "/opt/conda/envs/llama/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/llama/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 157, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
  0%|                                                                                                        | 0/30000 [00:00<?, ?it/s]
```

Forcing the inputs on the first cuda device, see below, does not  fix the issue.
```
    def compute_loss(self, model, inputs, return_outputs=False):
        return model(
            input_ids=inputs["input_ids"].to(f'cuda:{model.device_ids[0]}'),
            attention_mask=torch.ones_like(inputs["input_ids"]).to(f'cuda:{model.device_ids[0]}'),
            labels=inputs["input_ids"].to(f'cuda:{model.device_ids[0]}'),  # HF model does the slicing for us
        ).loss
```

**Comment by discoelysiumLW** [comment]
If you load the pre-trained model sequentially seems to fix the problem:
`model = transformers.AutoModelForCausalLM.from_pretrained(
        './llama-7b-hf',
        load_in_8bit=True,
         device_map='sequential',
    )`
